"""Tests for baseline generation: violations -> YAML config."""

from __future__ import annotations

import yaml

from dbt_linter.baseline import generate_baseline
from dbt_linter.models import Violation


def _violation(rule_id: str, resource_id: str) -> Violation:
    return Violation(
        rule_id=rule_id,
        resource_id=resource_id,
        resource_name=resource_id.split(".")[-1],
        message="test",
        severity="warn",
        file_path="models/test.sql",
    )


class TestGenerateBaseline:
    """Unit tests for generate_baseline()."""

    def test_empty_violations_returns_empty_rules(self):
        result = generate_baseline([])
        parsed = yaml.safe_load(result)
        assert parsed == {"rules": {}}

    def test_single_rule_single_resource(self):
        violations = [_violation("documentation/undocumented-models", "model.pkg.stg_users")]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        assert parsed == {
            "rules": {
                "documentation/undocumented-models": {
                    "exclude_resources": ["model.pkg.stg_users"],
                },
            },
        }

    def test_single_rule_multiple_resources(self):
        violations = [
            _violation("documentation/undocumented-models", "model.pkg.stg_users"),
            _violation("documentation/undocumented-models", "model.pkg.fct_orders"),
        ]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        resources = parsed["rules"]["documentation/undocumented-models"]["exclude_resources"]
        assert sorted(resources) == ["model.pkg.fct_orders", "model.pkg.stg_users"]

    def test_multiple_rules(self):
        violations = [
            _violation("documentation/undocumented-models", "model.pkg.stg_users"),
            _violation("testing/missing-primary-key-tests", "model.pkg.fct_orders"),
        ]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        assert "documentation/undocumented-models" in parsed["rules"]
        assert "testing/missing-primary-key-tests" in parsed["rules"]

    def test_deduplicates_resources(self):
        """Same resource violating the same rule twice should appear once."""
        violations = [
            _violation("documentation/undocumented-models", "model.pkg.stg_users"),
            _violation("documentation/undocumented-models", "model.pkg.stg_users"),
        ]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        resources = parsed["rules"]["documentation/undocumented-models"]["exclude_resources"]
        assert resources == ["model.pkg.stg_users"]

    def test_rules_sorted_alphabetically(self):
        violations = [
            _violation("testing/missing-primary-key-tests", "model.pkg.a"),
            _violation("documentation/undocumented-models", "model.pkg.b"),
            _violation("modeling/source-fanout", "model.pkg.c"),
        ]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        rule_ids = list(parsed["rules"].keys())
        assert rule_ids == sorted(rule_ids)

    def test_resources_sorted_within_rule(self):
        violations = [
            _violation("documentation/undocumented-models", "model.pkg.z_model"),
            _violation("documentation/undocumented-models", "model.pkg.a_model"),
            _violation("documentation/undocumented-models", "model.pkg.m_model"),
        ]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        resources = parsed["rules"]["documentation/undocumented-models"]["exclude_resources"]
        assert resources == ["model.pkg.a_model", "model.pkg.m_model", "model.pkg.z_model"]

    def test_output_is_valid_yaml(self):
        violations = [
            _violation("documentation/undocumented-models", "model.pkg.stg_users"),
            _violation("testing/missing-primary-key-tests", "model.pkg.fct_orders"),
        ]
        result = generate_baseline(violations)
        parsed = yaml.safe_load(result)
        assert isinstance(parsed, dict)
        assert "rules" in parsed

    def test_output_contains_header_comment(self):
        result = generate_baseline([])
        assert "Generated by dbt-lint" in result
