"""Baseline generation: convert current violations into a suppressions config."""

from __future__ import annotations

from collections import defaultdict
from typing import Any

import yaml

from dbt_lint.models import Violation

HEADER = (
    "# Generated by dbt-lint --generate-baseline\n"
    "# These are existing violations being suppressed, not accepted.\n"
    "# Fix the underlying issues and remove entries as you go.\n"
    "# To permanently suppress a rule, move it to dbt-lint.yml instead.\n"
)


def _is_real_resource_id(resource_id: str) -> bool:
    """Check if a resource_id is a real dbt resource (not synthetic)."""
    return "." in resource_id and not resource_id.startswith("model_type:")


def generate_baseline(violations: list[Violation]) -> str:
    """Generate a YAML baseline config that suppresses all given violations.

    Groups violations by rule_id and collects unique resource_ids per rule.
    Rules with only synthetic resource_ids (e.g. coverage metrics) are
    disabled entirely. Output is sorted for deterministic, diff-friendly
    results.
    """
    by_rule: dict[str, set[str]] = defaultdict(set)
    for v in violations:
        by_rule[v.rule_id].add(v.resource_id)

    rules_section: dict[str, dict[str, Any]] = {}
    for rule_id in sorted(by_rule):
        real_ids = sorted(rid for rid in by_rule[rule_id] if _is_real_resource_id(rid))
        if real_ids:
            rules_section[rule_id] = {"exclude_resources": real_ids}
        else:
            rules_section[rule_id] = {"enabled": False}

    body = yaml.dump(
        {"rules": rules_section},
        default_flow_style=False,
        sort_keys=False,
    )
    return HEADER + body
