"""Baseline generation: convert current violations into a suppressions config."""

from __future__ import annotations

from collections import defaultdict

import yaml

from dbt_linter.models import Violation

HEADER = (
    "# Generated by dbt-lint --generate-baseline\n"
    "# New resources will still be checked against these rules.\n"
)


def generate_baseline(violations: list[Violation]) -> str:
    """Generate a YAML baseline config that suppresses all given violations.

    Groups violations by rule_id and collects unique resource_ids per rule.
    Output is sorted for deterministic, diff-friendly results.
    """
    by_rule: dict[str, set[str]] = defaultdict(set)
    for v in violations:
        by_rule[v.rule_id].add(v.resource_id)

    rules: dict[str, dict[str, list[str]]] = {}
    for rule_id in sorted(by_rule):
        rules[rule_id] = {
            "exclude_resources": sorted(by_rule[rule_id]),
        }

    body = yaml.dump(
        {"rules": rules},
        default_flow_style=False,
        sort_keys=False,
    )
    return HEADER + body
